export enum TrackActionType {
  READ_TRACKS_REQUEST = 'READ_TRACKS_REQUEST',
  READ_TRACKS_SUCCESS = 'READ_TRACKS_SUCCESS',
  READ_TRACKS_FAILURE = 'READ_TRACKS_FAILURE',
  CLEAR_TRACKS = 'CLEAR_TRACKS',
}
