export enum UserActionType {
  ATTEMPT_LOGIN_REQUEST = 'ATTEMPT_LOGIN_REQUEST',
  ATTEMPT_LOGIN_SUCCESS = 'ATTEMPT_LOGIN_SUCCESS',
  ATTEMPT_LOGIN_FAILURE = 'ATTEMPT_LOGIN_FAILURE',
  READ_USER_PROFILE_REQUEST = 'READ_USER_PROFILE_REQUEST',
  READ_USER_PROFILE_SUCCESS = 'READ_USER_PROFILE_SUCCESS',
  READ_USER_PROFILE_FAILURE = 'READ_USER_PROFILE_FAILURE',
  CHANGE_THEME_MODE = 'CHANGE_THEME_MODE',
  NEW_SNACK_BAR = 'NEW_SNACK_BAR',
  CLOSE_SNACK_BAR = 'CLOSE_SNACK_BAR',
}
